### ISSUE TITLE
xenorchestra_vm resource manage tags

### ISSUE THREAD

**Issue by d1rtym0nk3y** [terra-farm/terraform-provider-xenorchestra#101]
Would be great to be able to specify tags for created vm's (and other objects that support tags)

### Desired behaviour
 - The provider should ensure that tags specified on the resource exist in XOA.  
 - If a tag is removed from the TF resource the provider should attempt to remove it in XOA
 - The provider should not attempt to manage tags that have been manually added via XOA

**Comment by ddelnano** [comment]
Hey Chris, thanks for raising this issue and I agree that tags could be more widely used across many of the resources (currently on the `xenorchestra_sr` data source has a `tags` attribute).

Your first and second criteria are possible, however, `The provider should not attempt to manage tags that have been manually added via XOA` is not possible. It isn't feasible because Terraform won't have any way to distinguish removing a tag from the terraform code from a manually created tag not defined in code.

So I can absolutely implement this support but unfortunately I can't implement ignoring manually added tags.

**Comment by d1rtym0nk3y** [comment]
Having terraform be able to add tags would be a huge win 👍

Re: `the provider should not attempt to manage tags that have been manually added via XOA`

If I create a vm with tf; lets say with `tag:a` and `tag:b`. tf will store that in its state. If i then remove `tag:b` from my config, and apply the change it knows i've removed `tag:b`,  so the only action it should take is to ensure that `tag:b` is not present in the tags from XOA.  At the same time, it should ensure that `tag:a` is present.  All other tags should be ignored...

I think tf calls this a partial update ?

**Comment by ddelnano** [comment]
@d1rtym0nk3y terraform doesn't track state across runs. Meaning Terraform doesn't remember what tags it was initially created with. It only knows what is currently in the configuration and what exists in the XO api.

There is some support for using `ignore_changes` with [map data types](https://www.terraform.io/docs/configuration/meta-arguments/lifecycle.html#ignore_changes) (which tags would be). However, it only works with updates meaning you would need to add a placeholder value in your terraform code to have the ignore applied (see [this](https://github.com/hashicorp/terraform/pull/21788/files#diff-a65126630bd0edaac55809a895c301f341c7d21a3d723e29f28437a56b3ec345) for an example).

If you have a way to implement it, I'm all ears but from my experience developing a more than one terraform provider it's not possible.

**Comment by d1rtym0nk3y** [comment]
My misunderstanding then, I was under the impression tf tracked state between runs.
It probably is better to manage tags via tf config anyway

**Comment by ddelnano** [comment]
This will be available in the next release (v0.13.0). I'm going to try and get some other features in that release so it won't be available until later this week.

**Comment by ddelnano** [comment]
Sorry for the delay but v0.13.0 is now released.
