### ISSUE TITLE
Error while creating a new virtual machine

### ISSUE THREAD

**Issue by ultreiac** [terra-farm/terraform-provider-xenorchestra#105]
Hi, I am getting this error while running **terraform apply**:

**Error**: json: cannot unmarshal bool into Go struct field Vm.high_availability of type string

main.tf is  [here](https://github.com/terra-farm/terraform-provider-xenorchestra/files/5808069/maingit.tf.txt) 

Software:

- xo-server 5.18.3

- Terraform v0.14.2

Thx in advance

**Comment by ddelnano** [comment]
@ultreiac what version of the provider are you using? I see `~> 0.5` specified but what version is installed? If it's not the latest have you tried upgrading your provider version?

Please attach terraform debug logs by running `TF_LOG=debug terraform plan` to this issue.

**Comment by ddelnano** [comment]
Also I recommend you joining the Discord mentioned in the README. It will be much easier for us to debug this.

**Comment by ultreiac** [comment]
@ddelnano I upgraded to latest version the provider and Xen Orchestra and it is working.
