### ISSUE TITLE
Add hosts data source

### ISSUE THREAD

**Issue by ddelnano** [terra-farm/terraform-provider-xenorchestra#122]
We have a host data source, but as described in https://github.com/terra-farm/terraform-provider-xenorchestra/issues/109#issuecomment-773835812 I believe we can power more advanced use cases by adding the ability to filter and sort hosts.

**Comment by gohumble** [comment]
Hello, 

Filtering by tag / pool is possible by adding it to the filter parameter within the jsonrpc call. 

But is there any possibility to sort results from xo.getAllObjects?
I wasn't able to find anything about sorting online. Maybe you can help me out? 
[XOA only defines 3 parameters for getAllObjects.](https://github.com/vatesfr/xen-orchestra/blob/385984b1d8e8b61a8c78a61fb64be009d4374483/packages/xo-server/src/api/xo.js#L65)

So my best approach for this would be fetching unsorted and sorting within the provider. Are you okay with that?

**Comment by ddelnano** [comment]
Yea I don't think we have another option. This could be a feature request made to Xen Orchestra but for now we will need to sort in the provider.

**Comment by ddelnano** [comment]
This fix will be released in v0.19.0 of the provider. Thanks for all your help @gohumble!
