### ISSUE TITLE
Order of tags causes unnecessary updates

### ISSUE THREAD

**Issue by d1rtym0nk3y** [terra-farm/terraform-provider-xenorchestra#139]
if i create a vm with a set of tag like

    tags = [
        "backup:nightly",
        "ansible_group:k8s",
        "ansible_managed",
        "k8s:master",
        "env:qa"
    ]

And then do a tf plan again, tf reports that it want to update the tags as follows

      ~ tags                 = [
          - "env:qa",
            "backup:nightly",
            # (2 unchanged elements hidden)
            "k8s:master",
          + "env:qa",
        ]

Workaround is to reorder the tag in the tf template, moving `env:qa` to head of the list.  I can understand that XO may return the vm's tags in a different order than they were specified in TF, so it would be nice if the order could be ignored, as it doesn't seem like the ordering of tags is important

**Comment by ddelnano** [comment]
Hey @d1rtym0nk3y, thanks for raising this issue. The terraform provider is using a `TypeList` to store the tags, which enforces an order to the tags. I agree that they shouldn't need to be ordered and I'll take a look at this soon.

**Comment by ddelnano** [comment]
I have a PR open for this. It still needs some work but the fix is coming soon.

**Comment by ddelnano** [comment]
This will be available in v0.19.1 of the provider which will be released later tonight
