### ISSUE TITLE
SR data source

### ISSUE THREAD

**Issue by m0ps** [terra-farm/terraform-provider-xenorchestra#15]
Just as you provide PIF data source, maybe it will be a good idea to provide similar for SR?

**Comment by ddelnano** [comment]
Definitely :). I just haven't had the time yet. I'll get this working soon.

**Comment by MrOffline77** [comment]
Vote for this. Otherwise it's not possible to provision VM's to hosts with local-storage, without knowing all SR UUID's from somewhere. Or is there another option to accomplish this without a PIF Ressource for the SR UUID's ?

**Comment by dmcanally** [comment]
Has anyone found a workaround for this issue?

**Comment by ddelnano** [comment]
Sorry for the silence on this issue. I can probably set aside some time this weekend for implementing this.

**Comment by ddelnano** [comment]
@m0ps @dmcanally @MrOffline77 I have a PR open that has basic support for this. Right now it uses the Storage repository's `name_label` to identify it. You can see the example terraform code for it in the acceptance test I wrote [here](https://github.com/terra-farm/terraform-provider-xenorchestra/pull/31/files#diff-8988628c8179213427a7dfea14d19d0bR51). I'll have docs soon but that's the best thing I have to show off how it works for now.

Would this solve your use cases? I'm thinking it would be nice to filter down based on the storage repository's type as well (lvm, local storage, etc) but I wanted to start with something basic and get your feedback first before I spent more time on enhanced functionality.

**Comment by ddelnano** [comment]
Since I haven't heard any feedback on my proposal in #31 I'm going to move forward with it. It is a decent starting point and extra functionality can be added later if it doesn't solve the needs that led to this issue's creation.

**Comment by dmcanally** [comment]
Apologies for the lack of response on this (work and all). 

I was able to test and it is working as desired, so THANK YOU for the quick feature add.

`
data "xenorchestra_template" "template" {
    name_label = var.template
}

data "xenorchestra_pif" "pif" {
    device = eth0
    vlan   = -1
}

data "xenorchestra_sr" "sr" {
  name_label = "Local storage"

}

resource "xenorchestra_cloud_config" "xoa_cc" {
  name     = "Bootstrap"
  template = <<EOF
#cloud-init
...
EOF
}

resource "xenorchestra_vm" "xoa_vm" {
  count        = 1
  memory_max   = 17179869184
  cpus         = 2
  cloud_config = "${xenorchestra_cloud_config.xoa_cc.template}"
  name_label   = "vm00"
  template     = data.xenorchestra_template.template.id
  network {
	  network_id = data.xenorchestra_pif.pif.network
  }

  disk {
    sr_id      = data.xenorchestra_sr.sr.uuid
    name_label = "vm00"
    size       = 17179869184
  }
`

**Comment by dmcanally** [comment]
Update: So I run 3 nodes in my xen pool. The current implementation will only worked for a pool wide SR. This will not work for leveraging "Local storage" sr. Each time terraform runs, data.xenorchestra_sr.sr.name_label will potentially be populated by a different node's Local Storage SR.

**Comment by ddelnano** [comment]
@dmcanally thanks for the response. Sounds like we need to add `pool_id` to the sr data source and even add a pool data source (so that we don't need to pass pool ids).

Reopening and I'll find time to give this attention soon.

**Comment by dmcanally** [comment]
I was able to work around this for now by giving each of the "Local storage" sr's in my pool a unique name (i.e. "Local storage 1", "Local storage 2", "Local storage 3" etc). I then pass that to xenorchestra_sr via a variable. When you push an update, I'll test as soon as I can.

Thanks,
Denver

**Comment by ddelnano** [comment]
@dmcanally I have just created version 0.3.2 which adds an optional `pool_id` attribute (PR #37). Please upgrade and let me know if this behaves as expected. The change is covered by acceptance tests so I am confident it should work well.

I have created #36 as a follow up item so that you won't need to have all of your pool IDs hard coded in the terraform files. I intend to fix that soon.

**Comment by ddelnano** [comment]
I'm going to close this again since #37  and #36 have both been implemented. Please let me know what you think when you give this a try.
