### ISSUE TITLE
Client versions: problem 

### ISSUE THREAD

**Issue by Orpere** [terra-farm/terraform-provider-xenorchestra#19]
Error: Failed to instantiate provider "xenorchestra" to obtain schema: Incompatible API version with plugin. Plugin version: 4, Client versions: [5]

**Comment by ddelnano** [comment]
@Orpere can you please give me more context about how you generated that log and more information? I'm not sure where to begin with just that single log line.

**Comment by ddelnano** [comment]
I’m closing this since I don’t have enough info to address the problem. If you collect the additional info I’m happy to revisit this.
