### ISSUE TITLE
Unmarshal error destroying vm

### ISSUE THREAD

**Issue by bossmonkeyman** [terra-farm/terraform-provider-xenorchestra#199]
Attempting to destroy a vm resource results in the following error:

`Error: json: cannot unmarshal bool into Go value of type []interface {}`

The vm itself is actually successfully removed in XO. It is just the `terraform destroy` command that fails. If destroy is immediately run again after the error, the vm is correctly detected as removed and the command succeeds.

**Comment by ddelnano** [comment]
@bossmonkeyman thanks for the bug report. This is a dup of #196 and will be fixed in the next release.
