### ISSUE TITLE
Convert provider to use the new Terraform Plugin SDK

### ISSUE THREAD

**Issue by ringods** [terra-farm/terraform-provider-xenorchestra#21]
Hashicorp revealed a separate Terraform Plugin SDK and the company promotes for provider developers to migrate their code to use it.

Source:
https://www.terraform.io/docs/extend/plugin-sdk.html

**Comment by ddelnano** [comment]
@ringods thanks for the heads up. I was planning to migrate this to terraform 0.12 within the next week so I'll take care of this issue then (since it's a prerequisite).

**Comment by ddelnano** [comment]
This was done when I merged #23.
