### ISSUE TITLE
Support `destroyCloudConfigVdiAfterBoot` on the `xenorchestra_vm` resource

### ISSUE THREAD

**Issue by ddelnano** [terra-farm/terraform-provider-xenorchestra#228]
This is with regards to a discussion that happened in [Discord](https://discord.com/channels/704471459279667330/705514553437323360/1073893388237164585).

**Comment by 4censord** [comment]
The link does not seem to work for me, would you mind summarizing what this is supposed to do in a few sentences?

**Comment by olivierlambert** [comment]
`destoyCloudConfigVdiAfterBoot` should remove the cloud config drive after the VM is booted (ie when XO got all the tools information)

**Comment by ddelnano** [comment]
Olivier beat me to it, but I'll add summaries to any linked discord conversations in the future 👍

**Comment by TerAnYu** [comment]
How to use this function?
![image](https://github.com/terra-farm/terraform-provider-xenorchestra/assets/7056211/c8002f4b-66b0-46e4-82c1-a5840ee7182a)

**Comment by ddelnano** [comment]
@TerAnYu this is a feature request so the functionality has not existed yet.

This was implemented in #255 and will be released in v0.25.0 coming later this week.

**Comment by online01993** [comment]
> @TerAnYu this is a feature request so the functionality has not existed yet.
> 
> This was implemented in #255 and will be released in v0.25.0 coming later this week.

@ddelnano hi, any news?

**Comment by ddelnano** [comment]
Sorry for the late follow up on this. I will be making a release once #260 is merged. I'm hoping to merge that by the middle of this upcoming week.

**Comment by ddelnano** [comment]
@online01993 the v0.25.0 release will be ready in the next 30 mins or so.
