### ISSUE TITLE
Can't create VM without specifying an affinity_host - issue with an empty string

### ISSUE THREAD

**Issue by killroy1971** [terra-farm/terraform-provider-xenorchestra#243]
I'm trying to create a diskless VM. The VM creation part works, however I need to include an affinity_host line in my VM's configuration, so I used the data.xenorchestra_pool.pool.id item, which in my mind should allow the hypervisor to choose the best host within the Homelab pool. The VMs create, but they can't be started because the hypervisor never assigns a host to the VMs.

Ultimately, that's what I would like to do. Omit the affinity_host configuration item entirely, or specify the xenorchestra.host as "none" on the affinity_host line, and have the hypervisor choose the host.

main.tf has: 
data "xenorchetra.pool" "pool" {
  name_label = "Homelab"
}

vm.tf has:
...
  memory_max = 107374182400
  cpus = 2
  hvm_boot_firmware = "uefi"
  name_label = each.key
  name_description = each.value
  affinity_host = data.xenorchestra_pool.pool.id
  template = data.xenorchestra_template.talos_control.id

  network {
    network_id = data.xenorchestra_network.net.id
  }
...

**Comment by vlad-iliushin** [comment]
Same issue here, 

```
 Error: jsonrpc2: code 10 message: invalid parameters: {"errors":[{"instancePath":"/affinityHost","schemaPath":"#/properties/affinityHost/minLength","keyword":"minLength","params":{"limit":1},"message":"must NOT have fewer than 1 characters"},
```

**Comment by illethrias** [comment]
+1 with that issue

**Comment by olivierlambert** [comment]
Pinging @julien-f so we can fix this (likely in XO)

**Comment by ddelnano** [comment]
This is essentially the same root cause as #238 and my work in progress PR is one way to address this (#239). I unfortunately haven't had time to focus on that change and it still needs more work before it's ready to merge.

If there is a way to handle this on the XO side, that would be great.

**Comment by killroy1971** [comment]
Is the error message coming from the XO side, because of a requirement or because of how the VM is being created by terraform?

**Comment by ddelnano** [comment]
The error message is coming from XO. The api was recently updated to enforced that optional fields should be `null` rather than empty strings. See #231 for the link to the XO commits.

**Comment by marlluslustosa** [comment]
https://github.com/terra-farm/terraform-provider-xenorchestra/issues/231#issuecomment-1561804232

**Comment by killroy1971** [comment]
Sorry for the delay. Travel, work, and stuff. Plus, it's been nice outside in my area.

I ran across this in the documentation:
    # Prefer to run the VM on the primary pool instance
    affinity_host = data.xenorchestra_pool.pool.master
    network {
      network_id = data.xenorchestra_network.net.id
    }

This solves my problem, I can't say if this was added since I started playing with terraform or not. Either way, my problem is solved.

**Comment by OTonGitHub** [comment]
What on earth pool.master mean? What's the point of adding in pool via label as a data parameter then?

**Comment by nathanael-h** [comment]
It's the master node (=physical server) of a pool. Read more in XCP-ng and Xen-orchestra docs 😉

Le 14 février 2025 21:44:46 GMT+01:00, OTonGitHub ***@***.***> a écrit :
>OTonGitHub left a comment (vatesfr/terraform-provider-xenorchestra#243)
>
>What on earth pool.master mean? What's the point of adding in pool via label as a data parameter then?
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/vatesfr/terraform-provider-xenorchestra/issues/243#issuecomment-2660228740
>You are receiving this because you are subscribed to this thread.
>
>Message ID: ***@***.***>
-- 
Nathanaël 
Envoyé depuis /e/OS Mail.

**Comment by OTonGitHub** [comment]
@nathanael-h I apologize for my stupid comment, I later on read a lot, and understood it well and made a little template the next day here as well https://github.com/OTonGitHub/Terraform-XO to get started.

**Comment by olivierlambert** [comment]
There's no stupid questions, glad you managed to move forward!
