### ISSUE TITLE
Plugin crash when trying to pass a computed value for a mac address

### ISSUE THREAD

**Issue by TerAnYu** [terra-farm/terraform-provider-xenorchestra#247]
Hello!
The problem is exactly like here: https://issueantenna.com/repo/terra-farm/terraform-provider-xenorchestra/issues/191

![изображение](https://github.com/terra-farm/terraform-provider-xenorchestra/assets/7056211/96d8cc8a-ce44-4fd8-9423-4c3c3b0d5628)

Please advise how to resolve this issue.

**Comment by ddelnano** [comment]
This is addressed in v0.26.1
