### ISSUE TITLE
websocket: bad handshake

### ISSUE THREAD

**Issue by zee67** [terra-farm/terraform-provider-xenorchestra#250]
Error output: 
with provider["registry.terraform.io/terra-farm/xenorchestra"],
│   on provider.tf line 10, in provider "xenorchestra":
│   10: provider "xenorchestra" {

my terraform config is below:
```
terraform {
  required_providers {
    xenorchestra = {
      source = "terra-farm/xenorchestra"
    }
  }
}

# Configure the XenServer Provider
provider "xenorchestra" {
  # Must be ws or wss
  url      = "ws://$private IP 192.168.1.1/24" # Or set XOA_URL environment variable
  username = "$admin"              # Or set XOA_USER environment variable
  password = "$password"              # Or set XOA_PASSWORD environment variable

  # This is false by default and
  # will disable ssl verification if true.
  # This is useful if your deployment uses
  # a self signed certificate but should be
  # used sparingly!
  #insecure = <false|true>              # Or set XOA_INSECURE environment variable to any value
}
```

any suggestion will be helpful, I am building a homelab. 
Thank you!

**Comment by ddelnano** [comment]
Hi @zee67, can you run terraform with debug logging enabled and provide the full output? You can do this by re-running the command that triggered this error with the following environment variable set -- `TF_LOG=DEBUG`. This may print your credentials so please check the output and redact anything sensitive.

**Comment by ddelnano** [comment]
I'm closing this since the issue has been stale. I'm more than happy to help debug this if you can provide the diagnostic information I've requested above.

**Comment by jeffre** [comment]
I had a similar issue until I realized `url` needed to point to xoa and not xcp-ng.
