### ISSUE TITLE
Add duplicate PIF in the VM

### ISSUE THREAD

**Issue by marlluslustosa** [terra-farm/terraform-provider-xenorchestra#32]
The form described by @ddelnano here https://github.com/terra-farm/terraform-provider-xenorchestra/issues/27#issuecomment-570122139  only works with different PIFs. If I try to add two identical PIFs he won't accept.

My case: I have an eth5 with a configured VLAN. So sometimes I have to pass two interfaces to the same VM. But it is not working.
`main.tf:`

```
...

data "xenorchestra_pif" "pif" {
    device = "eth5"
    vlan   = 3020
}

data "xenorchestra_pif" "pif2" {
    device = "eth7"
    vlan   = 50
}

...

resource "xenorchestra_vm" "bar" {
    memory_max = 1073741824
    cpus  = 1
    cloud_config = "${xenorchestra_cloud_config.bar.template}"
    name_label = "VM-build-Terraform"
    name_description = "VM-terraform"
    template = "${data.xenorchestra_template.template.id}"
    network {
      network_id = "${data.xenorchestra_pif.pif.network}"
    }

    network {
      network_id = "${data.xenorchestra_pif.pif2.network}"
    }

    disk {
      sr_id = "0c931761-7885-53c3-13ba-3dddd4dd84b2"
      name_label = "Debian10-terraform"
      size = 4294967296
    }
```

Any idea?

**Comment by ddelnano** [comment]
@marlluslustosa can you please post you `terraform apply` logs with the following environment variable set `TF_LOG=debug`?

This seems to be an issue with the `xenorchestra_vm` resource and not the pif data sources. As I mentioned in #33, since this provider is relatively new and has only included functionality that I use regularly I don't think the `xenorchestra_vm` resource knows how to attach 2 network interfaces to a single VM.

I should have time over the next few days to look into implementing this new feature and sorry that the documentation isn't more clear about what is currently supported!

**Comment by marlluslustosa** [comment]
`main.tf`
```

data "xenorchestra_template" "template" {
    name_label = "Debian10-CloudInit"
}

#definicao da rede
data "xenorchestra_pif" "pif" {
    device = "eth5"
    vlan   = 3020
}

resource "xenorchestra_vm" "bar" {
    memory_max = 1073741824
    cpus  = 1
    cloud_config = "${xenorchestra_cloud_config.bar.template}" #cloud-init external file
    name_label = "VM-build-Terraform"
    name_description = "VM - provider Xen Orchestra"
    template = "${data.xenorchestra_template.template.id}" 
    network {
      network_id = "${data.xenorchestra_pif.pif.network}"
    }

    network {
      network_id = "${data.xenorchestra_pif.pif.network}"
    }

    disk {
      sr_id = "0c931761-7885-59c3-13ba-3dddd4dd84b2"
      name_label = "Debian10-terraform"
      size = 4294967296 #(4gb).
    }
}
```

terraform plan

```
...

      + core_os          = false
      + cpu_cap          = 0
      + cpu_weight       = 0
      + cpus             = 1
      + id               = (known after apply)
      + memory_max       = 1073741824
      + name_description = "VM criada a partir do terraform - usando provider Xen Orchestra"
      + name_label       = "VM-build-Terraform"
      + template         = "77c41878-5c1d-2719-ba4a-73beddf5d2d4"

      + disk {
          + name_label = "Debian10-terraform"
          + size       = 4294967296
          + sr_id      = "0c931761-7885-59c3-13ba-3dddd4dd84b2"
        }

      + network {
          + network_id = "e5e2d17b-70b8-08e5-6c50-483f81e652b3"
        }
    }

```

TF_LOG:
https://bin.disroot.org/?3aa40c4718df1638#3doUi8iQobi35F24EFGa4Xy63rUEbhGpJwbuBgjSnk9y

**Comment by ddelnano** [comment]
This should be fixed in #54 and is available in version v0.4.0 of the provider. Please let me know if it doesn't solve your use case!

**Comment by marlluslustosa** [comment]
thanks for the effort! :+1:

**Comment by olivierlambert** [comment]
@marlluslustosa also if you have a repo somewhere or feedback on your real use cases, it's very welcome! At some point, we'll document it officially in XCP-ng or XO doc, and more feedback means better doc!

**Comment by marlluslustosa** [comment]
I am currently implemented in an internal environment and have been successful.
Soon I will add the files to my public repository and I am also offering to contribute to the official documentation soon.

Hugs! :)

**Comment by olivierlambert** [comment]
Great, eager to see that!
