### ISSUE TITLE
xoa_vm resource does not implement updates that can be applied without a VM halt

### ISSUE THREAD

**Issue by marlluslustosa** [terra-farm/terraform-provider-xenorchestra#35]
I'm testing terraform features, like changing the state of a VM, like its name. After the VM is provisioned, I try to make a change of state by changing its name_label within the .tf file and running a new `terraform apply`. After executing this, terraform tells me that it changed the name of the VM, it is even shown in the output of the `terraform show`, but it is fictitious information because when I go there on the Xen Orchestra panel the VM is still with the same old name label.

How can this problem be solved?

**Comment by ddelnano** [comment]
@marlluslustosa the vm resource unfortunately does nothing on updates. Because the development of this project was mostly driven by the features I use most I haven't implemented this yet. I have updated this issues title to reflect the feature improvement and I will look into implementing this soon!

Really appreciate all the feedback you've given me through using the project!

**Comment by marlluslustosa** [comment]
Sorry if I'm being too boring. lol
I like to test many of the tools I use. In this respect I like to be an avant-garde person and I saw that your project has a lot of future with the Xen Orchestra community.

I hope my contributions help to improve and give more ideas to this provider.

**Comment by ddelnano** [comment]
I'm going to split this into a few different issues. The VM resource has a significant amount of complexity (some options can only be applied if the VM is shutdown, others at runtime, etc).

I've created #40 for the updates that require the VM to be shutdown first and I've updated this issue to reflect updates that can be done without halting the VM.

**Comment by ddelnano** [comment]
This was completed in #144. There are still more vm resource update improvements to make (#145), however, the ability to hook into rebooting a VM to apply updates exists and works for CPU and memory updates.

**Comment by marlluslustosa** [comment]
Excellent!
:)

**Comment by ddelnano** [comment]
Sorry it took a while :)
