### ISSUE TITLE
xoa_vm resource does not implement updates for attributes that require halting the VM

### ISSUE THREAD

**Issue by ddelnano** [terra-farm/terraform-provider-xenorchestra#40]
Attributes like memory and cpu require the VM to be halted before they can be applied. Since that is more complexity than updating the simpler attributes at runtime I am going to accomplish this separate from #35

**Comment by olivierlambert** [comment]
In theory, it can be done live IF it's within some boundaries: can change vCPU numbers from 1 to max vCPU. Memory can be change within the dynamic range, capped by static range.

But it's complicated. I suppose it's more reasonable to do that when they are powered off.

**Comment by ddelnano** [comment]
Yea I still haven't fully grokked all the cpu and memory settings for VMs yet. I think that would be a great optimization (and I'll make sure to create a separate issue for it) but for now I will focus on making these updates possible and then edge cases can be made better in the future.

**Comment by ddelnano** [comment]
This has been addressed in #144. I implemented the online resizing of CPU and memory when possible. For updates that require the VM to be halted, terraform will stop the VM perform the full `vm.set` and then restart the VM.
