### ISSUE TITLE
Need VIF resource

### ISSUE THREAD

**Issue by dgmcdona** [terra-farm/terraform-provider-xenorchestra#50]
I would love to see support for creating/destroying/assigning SDNs. This would make possible the creation of much more complex networks between VMs.

**Comment by olivierlambert** [comment]
I'm not sure to get it.

A `VIF` object is a link between a `network` and a `VM`, as you can see here:

![](https://xapi-project.github.io/xen-api/classes.png)

What do you mean by "need VIF resource"?

**Comment by ddelnano** [comment]
@dgmcdona this should be fixed in #54 and is available in version v0.4.0 of the provider.

**Comment by dgmcdona** [comment]
@ddelnano thanks! Can’t wait to check it out tomorrow.

**Comment by ddelnano** [comment]
If this doesn't solve your use case please reopen and let me know what is missing!
