### ISSUE TITLE
Documenting the provider

### ISSUE THREAD

**Issue by ringods** [terra-farm/terraform-provider-xenorchestra#8]
Hello @ddelnano,

To document your provider, you can build upon the shoulders of common work done. The [Terra-Farm](https://terra-farm.github.io) website uses [Antora](https://antora.org) to build a single website out of sources spread over multiple Git repositories. The idea is to have a single website containing general documentation about the Terra-Farm initiative, the documentation of all providers (with different versions) and the documentation of all modules (with different versions).

To document your Terraform provider, mimic the setup as in the other 2 providers:
* [XenServer](https://github.com/terra-farm/terraform-provider-xenserver/tree/master/modules)
* [VirtualBox](https://github.com/terra-farm/terraform-provider-virtualbox/tree/master/modules)

Content is written in [AsciiDoc](https://asciidoctor.org/docs/asciidoc-writers-guide/) rather than Markdown.

The current site is still very barebones. Switching to the docs of a provider can be done in the menu on the bottom left at the moment.

I am working on making a better theme for the website. As an example, the [CouchBase docs](https://docs.couchbase.com) is also built with Antora, just with a nicer theme.

If something is not clear, add a comment to this issue and @-mention me and I chime in.

**Comment by ddelnano** [comment]
@ringods yea I’ve been looking into how those docs are setup. Honestly that is the main motivator that I transferred my repo into the terra-farm org. I’m eager to enhance my provider’s docs so I’ll be getting this setup this week.

**Comment by ringods** [comment]
@ddelnano let me know when you have a few basic files checked in in your repo and I will add the repo as an additional source here:

https://github.com/terra-farm/terra-farm.github.io/blob/site/site.yml#L5-L12

**Comment by ddelnano** [comment]
The first set of documentation is live so I'm calling this done.
