### ISSUE TITLE
xenorchestra_cloud_config and template_file

### ISSUE THREAD

**Issue by brd** [terra-farm/terraform-provider-xenorchestra#85]
I am trying to template my cloud-init config so I can pass in the hostname.  I am not sure if I am going about this the wrong way or if something like this should be possible.  I would like to pass a template_file into the xenorchestra_cloud_config resource, but it expects a string instead of an object.

When trying this:

```
data template_file "cloudinit" {
  for_each = var.vms
  template = file("cloud-config.tpl")
  vars = {
    hostname = "${each.value.hostname}"
  }
}

resource "xenorchestra_cloud_config" "test" {
  name = "cloud config name"
  for_each = var.vms
  template = data.template_file.cloudinit[each.key]
}
```

I get the following error:

```
Error: Incorrect attribute value type

  on main.tf line 46, in resource "xenorchestra_cloud_config" "test":
  46:   template = data.template_file.cloudinit[each.key]
    |----------------
    | data.template_file.cloudinit is object with 1 attribute "nomad"
    | each.key is "nomad"

Inappropriate value for attribute "template": string required.
```

Thanks for looking!

**Comment by ddelnano** [comment]
You need to use the rendered attribute on the `template_file` https://registry.terraform.io/providers/hashicorp/template/latest/docs/data-sources/file#rendered. That will give you the template content as a string.

**Comment by ddelnano** [comment]
Happy to continue to debug this but I'm going to close this issue since this appears to be more general help rather than a bug or improvement to the provider.

**Comment by brd** [comment]
Is this what you mean?

```
resource "xenorchestra_cloud_config" "test" {
  name = "cloud config name"
  for_each = var.vms
  template = data.template_file.cloudinit[each.key].rendered
}
```

That gives:

```
Error: Unsupported attribute

  on main.tf line 65, in resource "xenorchestra_vm" "allvms":
  65:   cloud_config = xenorchestra_cloud_config.test[each.key].rendered
    |----------------
    | each.key is "nomad"
    | xenorchestra_cloud_config.test is object with 1 attribute "nomad"

This object does not have an attribute named "rendered".
```

**Comment by ddelnano** [comment]
The `xenorchestra_cloud_config` resource doesn't have a `rendered` attribute. You need to use the following:

> cloud_config = xenorchestra_cloud_config.test[each.key].template

**Comment by brd** [comment]
Aha, that worked.  Thank you!
