### ISSUE TITLE
Add support for generating terraform files from existing infrastructure (terraformer support, reverse terraform)

### ISSUE THREAD

**Issue by userbradley** [terra-farm/terraform-provider-xenorchestra#96]
This is a continuation of [this issue](https://github.com/ddelnano/terraform-provider-xenorchestra-intro/issues/1) to have a terraform import.

Items to import would be:

- VM's
- networks
-SR's 
-Disks

These seem to be the most used items that I would want to manage through IaC

**Comment by ddelnano** [comment]
I have an initial implementation of this with #138 and https://github.com/GoogleCloudPlatform/terraformer/pull/846. Initially, this will only support the `xenorchestra_acl` and `xenorchestra_resource_set` resources.

The resources you mentioned are definitely important to support but have the following problems at the moment:
- VM - this resource is the most complex and until some issues are fixed (like #100) the generation process will likely result in terraform code that will need to be manually tweaked. I intend to support this but it would require lots of testing and so for the initial support I decided it was outside the scope
- Network - there is no network resource until #119 is implemented
- SR - there is no storage repository resource until # is implemented
- Disks - there is no vdi resource at the moment

While the resources you named won't be included in the initial support, getting the project working with terraformer with a few resources is a good first step.

**Comment by ddelnano** [comment]
Binaries are now available on the terraformer project as of [0.8.12](https://github.com/GoogleCloudPlatform/terraformer/releases/tag/0.8.12). I'll write up some instructions on how to use this and then I think the initial support can be considered complete.

I'll likely track the future improvements for the VM, network, sr and disk resources in a new issue.

**Comment by userbradley** [comment]
Awesome work! 

Sorry it took so long to get back to this.
